### PR TITLE
Update versions and add dependencies list in README.md.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/jvm-toxcore-c/12)

### CODE REVIEW

**Comment by zoff99** [comment]
:lgtm_strong:

---

Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/jvm-toxcore-c/12#-:-K_-Bp7daXnIIbrsOeR3:b-jbsf8z)*

**Comment by zoff99** [comment]
ok here is something wrong :-(
no targets in travis

**Comment by iphydf** [comment]
Worse: it looks like sbt-plugins 0.1.2 doesn't work. I don't know what's going wrong, but it can't find the native library for tests. It works locally on my machine..

**Comment by iphydf** [comment]
It was a bug in sbt-plugins. Fixed now.

**Pull request merged**
